set_languages("c++23")
add_requires("opencv", "asio", "spdlog", "yaml-cpp")
target("cv")
    set_kind("binary")
    add_files("src/**.cpp")
    add_includedirs("include")
    add_packages("opencv", "asio", "spdlog", "yaml-cpp")
    set_configdir("$(buildir)/$(plat)/$(arch)/$(mode)")
    add_configfiles("config/*.yaml", {onlycopy = true})